[package]
name = "ggraphics"
version = "0.0.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]
edition = "2018"
description = "A 2d graphics library (tentative)"
license = "MIT"


[dependencies]
image = "0.21"
log = "0.4"
winit = "0.19"
rendy = {version = "0.2", features=["texture-image", "vulkan"]}
#rendy = {git="https://github.com/amethyst/rendy.git", rev="5c35277f9080e0ea8b73096f62ddb399cf73820a", features=["texture-image", "vulkan"]}
failure = "0.1"
euclid = "0.19"


palette = "0.4"
rand = "0.6"
